CREATE TABLE accounts(
  accountNumber INT UNIQUE NOT NULL PRIMARY KEY ,
  customerName VARCHAR(100) NOT NULL,
  balance FLOAT NOT NULL DEFAULT 0,
  password VARCHAR(255) NOT NULL,
  createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type ENUM('SAVINGS', 'CURRENT') DEFAULT 'CURRENT'
);

CREATE TABLE transactions(
    txnHash BIGINT UNIQUE NOT NULL PRIMARY KEY,
    accountNumber INT NOT NULL,
    amount INT NOT NULL,
    mode ENUM('CREDIT', 'DEBIT') NOT NULL,
    createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (accountNumber) REFERENCES accounts(accountNumber) ON DELETE CASCADE
)